# DESCRIPTION:
# mk module to plot a chord diagram of the human genome 
# from two BED files of Differentially Interacting Regions.
#
# USAGE:
# Single target execution: `mk <TARGET>` where TARGET is
# any line printed by the script `bin/mk-targets`
#
# Multiple target execution in tandem `bin/mk-targets | xargs mk`
#
# AUTHOR: HRG
#
# read in config file
<config.mk
#
# Run R script to generate chord diagram from BEDs.
#
results/%.chord_diagram.png:	data/%.bed1.sigpairs.table.Rds data/%.bed2.sigpairs.table.Rds
	mkdir -p `dirname $target`
	bin/plot-chord-diagram.R \
		--input_bed1 data/$stem.bed1.sigpairs.table.Rds \
		--input_bed2 data/$stem.bed2.sigpairs.table.Rds \
		--output_plot $target \
		--each_chromosome $plot_each_chromosome

